import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/custom/Footer";
import Navbar from "./components/custom/Navbar";
import Hero from "./components/custom/Hero";
import Skill from "./components/custom/skill";
import About from "./components/custom/about";
import Project from "./components/custom/project";
import Contact from "./components/custom/contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Hero />
        <About />
        <Skill />
        <Project />
        <Contact />
        {children}
        <Footer />
        </body>
    </html>
  );
}
